#include "english.h"
#include "ionglish.h"
#include "winglish.h"

MAKE GENERIC_FUNCTION ALLOCCONSOLE P_START GENERIC START_IMPLEMENTATION

ALLOCATE_CONSOLE
REOPEN_FILE CONSOLE_OUTPUT, WRITE_FILE, STANDARD_OUTPUT P_END
REOPEN_FILE CONSOLE_INPUT, READ_FILE, STANDARD_INPUT P_END
REOPEN_FILE CONSOLE_OUTPUT, WRITE_FILE, STANDARD_ERROR P_END

END_IMPLEMENTATION

MAKE GENERIC_FUNCTION SHUTCONSOLE P_START GENERIC START_IMPLEMENTATION

CLOSE_CONSOLE

END_IMPLEMENTATION

S_WIN

CALL ALLOCCONSOLE P_NONE END

PRINT "Hey this works\n" P_END
CONSOLE PAUSE_CONSOLE P_END

CALL SHUTCONSOLE P_NONE END

END_PROGRAM_WITH(0)