#include "english.h"

S_PROGRAM
    CONSTANT CLET POINTER HEY IS "Wow, this is cool" END
    CONSTANT CLET POINTER LOL IS "Yay" END
    ILET A IS 2 END
    CALL MBOX P_START 0, HEY, LOL, MB_OK P_END
END_PROGRAM_WITH(A)