#include "english.h"
#include "glfwenglish.h"
#include "ionglish.h"
#include "winglish.h"
/* S_PROGRAM
    CONSTANT CLET POINTER HEY IS "Wow, this is cool" END
    CONSTANT CLET POINTER LOL IS "Yay" END
    ILET A IS 2 END
    CALL MBOX P_START 0, HEY, LOL, MB_OK P_END
END_PROGRAM_WITH(A) */

/* S_PROGRAM

IF CANNOT START_GLFW THEN STOP_WITH_CODE(1) ENDIF
MAKE WINDOW WITH POINTER AS WIN END
MAKE WIN EQUALS_TO MAKE_WIN P_START 1280, 720, "Test", NONE, NONE P_END
WHEN SHOULDNT BE CLOSED(WIN) THEN 
    SWAP_BUFFERS_ON(WIN)
    DO_POLLING
END_WHEN

SHUT_WIN(WIN) END
SHUT_GLFW END

END_PROGRAM */

MAKE GENERIC_FUNCTION ALLOCCONSOLE P_START GENERIC START_IMPLEMENTATION

ALLOCATE_CONSOLE
REOPEN_FILE CONSOLE_OUTPUT, WRITE_FILE, STANDARD_OUTPUT P_END
REOPEN_FILE CONSOLE_INPUT, READ_FILE, STANDARD_INPUT P_END
REOPEN_FILE CONSOLE_OUTPUT, WRITE_FILE, STANDARD_ERROR P_END

END_IMPLEMENTATION

MAKE GENERIC_FUNCTION SHUTCONSOLE P_START GENERIC START_IMPLEMENTATION

CLOSE_CONSOLE

END_IMPLEMENTATION

S_WIN

CALL ALLOCCONSOLE P_NONE END

PRINT "Hey this works\n" P_END
CONSOLE PAUSE_CONSOLE P_END

CALL SHUTCONSOLE P_NONE END

END_PROGRAM_WITH(0)